export const data = {
  ofertas: [
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
  ],
  pedidos: [
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
  ],
  eventos: [
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
  ],
  capacitaciones: [
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
    {
      mainImageUrl: '',
      logo: '',
      businessName: '',
      review: 0,
      location: '',
      type: '',
      title: '',
      description: '',
      moreDetails: '',
    },
  ],
};
